default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: gestao
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: api_gestao_development

test:
  <<: *default
  database: api_gestao_test

production:
  <<: *default
  database: api_gestao_production
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>
