services:
  db:
    image: postgres:15
    container_name: postgres_api_gestao
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: gestao
      POSTGRES_PASSWORD: password
      POSTGRES_DB: api_gestao_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
